#!/usr/bin/env python3
"""Logic_cartridge_melissa_mjcf.py — auto-generated by LegacyMotionEditor.

Generated: 2026-09-04 20:10:50
Source:    model/melissa_mjcf/melissa_mjcf.xml

Loaded by Meridian_console / PhysicalOn as a Logic Cartridge and run at
100 Hz (see LOOP_HZ). SYSTEM AREA = frozen MotionPlayer + Commander runtime.
USER WORK AREA / ProjectCode supplies controllers, params, and CALL helpers;
regenerated on every export.
"""

import json
import logging
import math
import os
import threading
import time
from dataclasses import dataclass, field, asdict

import numpy as np

# ── Joint name dictionary (auto-generated) ──────────────────────
JOINTS: dict[str, int] = {
    'C_HEAD'                : 21,
    'L_SHOULDER_PITCH'      : 23,
    'L_SHOULDER_ROLL'       : 25,
    'L_ELBOW_YAW'           : 27,
    'L_ELBOW_PITCH'         : 29,
    'L_HIPJOINT_XR'         : 33,
    'L_HIPJOINT_YP'         : 35,
    'L_KNEE_YP'             : 37,
    'L_ANKLE_YP'            : 39,
    'L_ANKLE_XR'            : 41,
    'C_CHEST'               : 51,
    'R_SHOULDER_PITCH'      : 53,
    'R_SHOULDER_ROLL'       : 55,
    'R_ELBOW_YAW'           : 57,
    'R_ELBOW_PITCH'         : 59,
    'R_HIPJOINT_XR'         : 63,
    'R_HIPJOINT_YP'         : 65,
    'R_KNEE_YP'             : 67,
    'R_ANKLE_YP'            : 69,
    'R_ANKLE_XR'            : 71,
}

# ── Meridim joint map (read by PhysicalOn) ────────────────────
MERIDIM_JOINT_MAP = [
    {"joint": 'c_spine_01_yp', "meridim":  51, "sign": +1.0, "role": 'servo'},
    {"joint": 'c_neck_zy', "meridim":  21, "sign": +1.0, "role": 'servo'},
    {"joint": 'l_shoulder_yp', "meridim":  23, "sign": +1.0, "role": 'servo'},
    {"joint": 'l_shoulder_xr', "meridim":  25, "sign": +1.0, "role": 'servo'},
    {"joint": 'l_elbow_zy', "meridim":  27, "sign": +1.0, "role": 'servo'},
    {"joint": 'l_elbow_yp', "meridim":  29, "sign": +1.0, "role": 'servo'},
    {"joint": 'r_shoulder_yp', "meridim":  53, "sign": +1.0, "role": 'servo'},
    {"joint": 'r_shoulder_xr', "meridim":  55, "sign": -1.0, "role": 'servo'},
    {"joint": 'r_elbow_zy', "meridim":  57, "sign": -1.0, "role": 'servo'},
    {"joint": 'r_elbow_yp', "meridim":  59, "sign": +1.0, "role": 'servo'},
    {"joint": 'l_hipjoint_xr', "meridim":  33, "sign": +1.0, "role": 'servo'},
    {"joint": 'l_hipjoint_yp', "meridim":  35, "sign": +1.0, "role": 'servo'},
    {"joint": 'l_knee_yp', "meridim":  37, "sign": +1.0, "role": 'servo'},
    {"joint": 'l_ankle_yp', "meridim":  39, "sign": +1.0, "role": 'servo'},
    {"joint": 'l_ankle_xr', "meridim":  41, "sign": +1.0, "role": 'servo'},
    {"joint": 'r_hipjoint_xr', "meridim":  63, "sign": -1.0, "role": 'servo'},
    {"joint": 'r_hipjoint_yp', "meridim":  65, "sign": +1.0, "role": 'servo'},
    {"joint": 'r_knee_yp', "meridim":  67, "sign": +1.0, "role": 'servo'},
    {"joint": 'r_ankle_yp', "meridim":  69, "sign": +1.0, "role": 'servo'},
    {"joint": 'r_ankle_xr', "meridim":  71, "sign": -1.0, "role": 'servo'},
]

# ── Servo max speed [deg/s] per Meridim slot (auto-generated) ────
# MotionPlayer clamps per-tick angular step to this rate so the
# cartridge trajectory matches LME 3D preview (which applies the
# same limit via PlaybackController._apply_joint_speed_limits).
# Default fallback: 300.0 deg/s (= DEFAULT_JOINT_SPEED).
JOINT_MAX_SPEED_DEG_S: dict[int, float] = {
     51:  352.942,  # c_spine_01_yp (KRS4034)
     21:  352.942,  # c_neck_zy (KRS4034)
     23:  352.942,  # l_shoulder_yp (KRS4034)
     25:  352.942,  # l_shoulder_xr (KRS4034)
     27:  352.942,  # l_elbow_zy (KRS4034)
     29:  352.942,  # l_elbow_yp (KRS4034)
     53:  352.942,  # r_shoulder_yp (KRS4034)
     55:  352.942,  # r_shoulder_xr (KRS4034)
     57:  352.942,  # r_elbow_zy (KRS4034)
     59:  352.942,  # r_elbow_yp (KRS4034)
     33:  352.942,  # l_hipjoint_xr (KRS4034)
     35:  352.942,  # l_hipjoint_yp (KRS4034)
     37:  352.942,  # l_knee_yp (KRS4034)
     39:  352.942,  # l_ankle_yp (KRS4034)
     41:  352.942,  # l_ankle_xr (KRS4034)
     63:  352.942,  # r_hipjoint_xr (KRS4034)
     65:  352.942,  # r_hipjoint_yp (KRS4034)
     67:  352.942,  # r_knee_yp (KRS4034)
     69:  352.942,  # r_ankle_yp (KRS4034)
     71:  352.942,  # r_ankle_xr (KRS4034)
}


# ══════════════════════════════════════════════════════════════════════════════
# SYSTEM AREA = frozen MotionPlayer + Commander runtime.
# Controllers / gait params / CALL helpers live in ProjectCode (USER WORK AREA).
# ══════════════════════════════════════════════════════════════════════════════

# ── Pad layout ────────────────────────────────────────────────────────────────
PAD_BTN_TRI    =  3   # △
PAD_BTN_CIR    =  1   # ○
PAD_BTN_CRS    =  0   # ×
PAD_BTN_SQR    =  2   # □
PAD_BTN_SELECT =  4   # SHARE / Select
PAD_BTN_START  =  5   # OPTIONS / Start
PAD_BTN_L3     =  6   # 左スティック押込
PAD_BTN_R3     =  7   # 右スティック押込
PAD_BTN_L1     =  9   # L1
PAD_BTN_R1     = 10   # R1
PAD_AXIS_LX    = 16   # left  stick X  (left=-1, right=+1)
PAD_AXIS_LY    = 17   # left  stick Y  (up=-1=fwd, down=+1=back)
PAD_AXIS_RX    = 18   # right stick X
PAD_AXIS_RY    = 19   # right stick Y
PAD_AXIS_L2V   = 20   # L2 analog trigger (0.0..1.0)
PAD_AXIS_R2V   = 21   # R2 analog trigger (0.0..1.0)
PAD_HAT_X      = 22   # D-pad X  (+1=right, -1=left)
PAD_HAT_Y      = 23   # D-pad Y  (+1=up, -1=down)
BTN_THRESH     = 0.5

_BTN_NAME_TO_PAD_IDX: dict[str, int] = {
    "L1":     PAD_BTN_L1,     "R1":     PAD_BTN_R1,
    "TRI":    PAD_BTN_TRI,    "CIR":    PAD_BTN_CIR,
    "SQR":    PAD_BTN_SQR,    "CRS":    PAD_BTN_CRS,
    "SELECT": PAD_BTN_SELECT, "START":  PAD_BTN_START,
    "L3":     PAD_BTN_L3,     "R3":     PAD_BTN_R3,
    # NOTE: L2 / R2 は analog trigger (pad[PAD_AXIS_L2V/R2V]) から
    #       BTN_THRESH で判定するため辞書には入れず、_eval_src の
    #       明示分岐で扱う。
}

# ── Meridim90 joint indices ───────────────────────────────────────────────────
IDX_L_SHOULDER_PITCH = 23;  IDX_L_SHOULDER_ROLL = 25
IDX_L_ELBOW_YAW      = 27;  IDX_L_ELBOW_PITCH   = 29
IDX_C_CHEST          = 51
IDX_R_SHOULDER_PITCH = 53;  IDX_R_SHOULDER_ROLL = 55
IDX_R_ELBOW_YAW      = 57;  IDX_R_ELBOW_PITCH   = 59
IDX_L_HIPJOINT_ZY = 31;  IDX_L_HIPJOINT_XR = 33;  IDX_L_HIPJOINT_YP = 35
IDX_L_KNEE_YP     = 37;  IDX_L_ANKLE_YP    = 39;  IDX_L_ANKLE_XR    = 41
IDX_R_HIPJOINT_ZY = 61;  IDX_R_HIPJOINT_XR = 63;  IDX_R_HIPJOINT_YP = 65
IDX_R_KNEE_YP     = 67;  IDX_R_ANKLE_YP    = 69;  IDX_R_ANKLE_XR    = 71

# ── Commander states ──────────────────────────────────────────────────────────
STATE_IDLE   = "IDLE"
STATE_MOTION = "MOTION"

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.WARNING,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
    handlers=[logging.StreamHandler()],
)
logger = logging.getLogger(__name__)

# ── Pad decoder ───────────────────────────────────────────────────────────────
def _decode_meridim_pad(s: list) -> list:
    """s_meridim[15..18] → 24-element pad list."""
    pad = [0.0] * 24
    bitmask = int(float(s[15])) & 0xFFFF
    # bit → pad-list slot (see PAD_BTN_* constants below).
    for bit, idx in {
        4096: 3, 8192: 1, 16384: 0, 32768: 2,   # △○×□
        1024: 9, 2048: 10,                        # L1/R1
        1: 4, 8: 5,                               # Select/Start
        2: 6, 4: 7,                               # L3/R3
    }.items():
        if bitmask & bit:
            pad[idx] = 1.0
    if bitmask & 16:    pad[23] =  1.0
    elif bitmask & 64:  pad[23] = -1.0
    if bitmask & 32:    pad[22] =  1.0
    elif bitmask & 128: pad[22] = -1.0

    def _unpack(v):
        v = int(float(v)) & 0xFFFF
        lo = v & 0xFF;          lo = lo - 256 if lo >= 128 else lo
        hi = (v >> 8) & 0xFF;   hi = hi - 256 if hi >= 128 else hi
        return lo, hi

    ly, lx = _unpack(s[16])
    ry, rx = _unpack(s[17])
    pad[16] = lx / 127.0
    pad[17] = ly / 127.0
    pad[18] = rx / 127.0
    pad[19] = ry / 127.0
    v18 = int(float(s[18])) & 0xFFFF
    pad[20] = (v18 & 0xFF) / 255.0
    pad[21] = ((v18 >> 8) & 0xFF) / 255.0
    return pad


# ── Pad helper ────────────────────────────────────────────────────────────────
class Pad:
    """パッド入力をわかりやすく取得するヘルパー。
    使い方: pad = Pad(s)   → pad.l1 / pad.tri / pad.lx / pad.ly
    """
    def __init__(self, s: list) -> None:
        raw     = _decode_meridim_pad(s)
        bitmask = int(float(s[15])) & 0xFFFF
        self.tri      = bool(bitmask & 4096)
        self.cir      = bool(bitmask & 8192)
        self.crs      = bool(bitmask & 16384)
        self.sqr      = bool(bitmask & 32768)
        self.l1       = bool(bitmask & 1024)
        self.r1       = bool(bitmask & 2048)
        self.l3       = bool(bitmask & 2)
        self.r3       = bool(bitmask & 4)
        self.select   = bool(bitmask & 1)
        self.start    = bool(bitmask & 8)
        self.hat_up   = bool(bitmask & 16)
        self.hat_down = bool(bitmask & 64)
        self.hat_r    = bool(bitmask & 32)
        self.hat_l    = bool(bitmask & 128)
        self.lx  = raw[PAD_AXIS_LX]
        self.ly  = raw[PAD_AXIS_LY]
        self.rx  = raw[PAD_AXIS_RX]
        self.ry  = raw[PAD_AXIS_RY]
        self.l2v = raw[PAD_AXIS_L2V]
        self.r2v = raw[PAD_AXIS_R2V]
        # L2/R2 のデジタル判定は analog トリガーのしきい値で行う (PadMonitor と同じ挙動)。
        self.l2  = self.l2v > BTN_THRESH
        self.r2  = self.r2v > BTN_THRESH


# ── Joint helpers ─────────────────────────────────────────────────────────────
def get_angle(meridim: list, joint_name: str) -> float:
    """関節角度 [deg] を取得する。JOINTS の辞書キーを使う。"""
    idx = JOINTS.get(joint_name)
    if idx is None:
        raise KeyError(f"Joint '{joint_name}' not in JOINTS dict")
    return float(meridim[idx]) / 100.0


def set_angle(s: list, joint_name: str, deg: float) -> None:
    """関節角度コマンドを s_meridim に書き込む。トルクフラグも同時に立てる。"""
    idx = JOINTS.get(joint_name)
    if idx is None:
        raise KeyError(f"Joint '{joint_name}' not in JOINTS dict")
    s[idx - 1] = 1.0
    s[idx]     = float(deg) * 100.0


def get_imu(r: list) -> dict:
    """IMUデータを辞書で返す (PhysicalOn の MuJoCo 仮想IMU値)。"""
    return {
        "ax": float(r[2])  / 100.0, "ay": float(r[3])  / 100.0,
        "az": float(r[4])  / 100.0,
        "gx": float(r[5])  / 100.0, "gy": float(r[6])  / 100.0,
        "gz": float(r[7])  / 100.0,
        "roll":  float(r[12]) / 100.0,
        "pitch": float(r[13]) / 100.0,
        "yaw":   float(r[14]) / 100.0,
    }


# ── MotionPlayer ──────────────────────────────────────────────────────────────
def _apply_easing(idx: int, t: float) -> float:
    """Apply easing function by index (matches LME EASING_PRESETS order)."""
    t = max(0.0, min(1.0, t))
    if idx == 0:  return t
    if idx == 1:  return 1 - math.cos(t * math.pi / 2)
    if idx == 2:  return math.sin(t * math.pi / 2)
    if idx == 3:  return -(math.cos(math.pi * t) - 1) / 2
    if idx == 4:  return t * t
    if idx == 5:  return 1 - (1 - t) * (1 - t)
    if idx == 6:  return 2 * t * t if t < 0.5 else 1 - (-2 * t + 2) ** 2 / 2
    if idx == 7:  return t ** 3
    if idx == 8:  return 1 - (1 - t) ** 3
    if idx == 9:  return 4 * t ** 3 if t < 0.5 else 1 - (-2 * t + 2) ** 3 / 2
    if idx == 10: return t ** 4
    if idx == 11: return 1 - (1 - t) ** 4
    if idx == 12: return 8 * t ** 4 if t < 0.5 else 1 - (-2 * t + 2) ** 4 / 2
    if idx == 13: return t ** 5
    if idx == 14: return 1 - (1 - t) ** 5
    if idx == 15: return 16 * t ** 5 if t < 0.5 else 1 - (-2 * t + 2) ** 5 / 2
    if idx == 16: return 0.0 if t == 0 else (2 ** (10 * t - 10) if t < 1 else 1.0)
    if idx == 17: return 1.0 if t == 1 else 1 - 2 ** (-10 * t)
    if idx == 18:
        if t == 0: return 0.0
        if t == 1: return 1.0
        return 2 ** (20 * t - 10) / 2 if t < 0.5 else (2 - 2 ** (-20 * t + 10)) / 2
    if idx == 19: return 1 - math.sqrt(max(0.0, 1 - t * t))
    if idx == 20: return math.sqrt(max(0.0, 1 - (t - 1) ** 2))
    if idx == 21:
        return (1 - math.sqrt(max(0.0, 1 - (2 * t) ** 2))) / 2 if t < 0.5 \
            else (math.sqrt(max(0.0, 1 - (-2 * t + 2) ** 2)) + 1) / 2
    if idx == 22:  # easeInBack
        c1 = 1.70158; c3 = c1 + 1
        return c3 * t * t * t - c1 * t * t
    if idx == 23:  # easeOutBack
        c1 = 1.70158; c3 = c1 + 1
        return 1 + c3 * ((t - 1) ** 3) + c1 * ((t - 1) ** 2)
    if idx == 24:  # easeInOutBack
        c1 = 1.70158; c2 = c1 * 1.525
        if t < 0.5: return ((2 * t) ** 2 * ((c2 + 1) * 2 * t - c2)) / 2
        return (((2 * t - 2) ** 2) * ((c2 + 1) * (t * 2 - 2) + c2) + 2) / 2
    if idx == 25:  # easeInElastic
        if t == 0: return 0.0
        if t == 1: return 1.0
        return -(2 ** (10 * t - 10)) * math.sin((t * 10 - 10.75) * (2 * math.pi / 3))
    if idx == 26:  # easeOutElastic
        if t == 0: return 0.0
        if t == 1: return 1.0
        return (2 ** (-10 * t)) * math.sin((t * 10 - 0.75) * (2 * math.pi / 3)) + 1
    if idx == 27:  # easeInOutElastic
        if t == 0: return 0.0
        if t == 1: return 1.0
        c5 = 2 * math.pi / 4.5
        if t < 0.5: return -((2 ** (20 * t - 10)) * math.sin((20 * t - 11.125) * c5)) / 2
        return ((2 ** (-20 * t + 10)) * math.sin((20 * t - 11.125) * c5)) / 2 + 1
    if idx == 28:  # easeInBounce (= 1 - easeOutBounce(1-t))
        x = 1.0 - t; n1 = 7.5625; d1 = 2.75
        if x < 1 / d1: r = n1 * x * x
        elif x < 2 / d1: x -= 1.5 / d1; r = n1 * x * x + 0.75
        elif x < 2.5 / d1: x -= 2.25 / d1; r = n1 * x * x + 0.9375
        else: x -= 2.625 / d1; r = n1 * x * x + 0.984375
        return 1 - r
    if idx == 29:  # easeOutBounce
        n1 = 7.5625; d1 = 2.75
        if t < 1 / d1: return n1 * t * t
        if t < 2 / d1: t -= 1.5 / d1; return n1 * t * t + 0.75
        if t < 2.5 / d1: t -= 2.25 / d1; return n1 * t * t + 0.9375
        t -= 2.625 / d1; return n1 * t * t + 0.984375
    if idx == 30:  # easeInOutBounce
        n1 = 7.5625; d1 = 2.75
        if t < 0.5:
            x = 1 - 2 * t
            if x < 1 / d1: r = n1 * x * x
            elif x < 2 / d1: x -= 1.5 / d1; r = n1 * x * x + 0.75
            elif x < 2.5 / d1: x -= 2.25 / d1; r = n1 * x * x + 0.9375
            else: x -= 2.625 / d1; r = n1 * x * x + 0.984375
            return (1 - r) / 2
        x = 2 * t - 1
        if x < 1 / d1: r = n1 * x * x
        elif x < 2 / d1: x -= 1.5 / d1; r = n1 * x * x + 0.75
        elif x < 2.5 / d1: x -= 2.25 / d1; r = n1 * x * x + 0.9375
        else: x -= 2.625 / d1; r = n1 * x * x + 0.984375
        return (1 + r) / 2
    return 2 * t * t if t < 0.5 else 1 - (-2 * t + 2) ** 2 / 2  # fallback: easeInOutQuad

_MP_MAX_INSTANT = 100

# Fallback if a legacy cartridge did not inject JOINT_MAX_SPEED_DEG_S before
# SYSTEM_AREA. 300 deg/s matches LME's DEFAULT_JOINT_SPEED. Freshly exported
# cartridges always define the dict per-joint above, so this is a safety net.
_DEFAULT_MAX_SPEED_DEG_S = 300.0
try:
    JOINT_MAX_SPEED_DEG_S
except NameError:
    JOINT_MAX_SPEED_DEG_S = {}

class MotionPlayer:
    """POS/CMP/JUMP/SET セグメントによるキーフレームモーション再生エンジン。

    POS  ({joint_idx: angle_deg, ...}, time_ms)
    CMP  ("CMP", src, op, value, branch_line, next_line)
    JUMP ("JUMP", line_no)  /  ("JUMP", motion_ref, line_no)
    SET  ("SET", var_name, op, value)
    """

    def __init__(self, segments: list, base_data: list, loop_hz: int = 100,
                 variables: dict | None = None, start_line: int = 0) -> None:
        self._segments   = segments
        self._data       = list(base_data)
        self._frame_dt   = 1000.0 / loop_hz
        self._pc         = start_line
        self._last_pc    = -1
        self._tmr        = 0.0
        self._next_ms    = 0.0
        self._last: dict[int, float] = {}
        self._variables  = variables if variables is not None else {}
        self._jump_target: tuple | None = None

    @property
    def data(self) -> list:
        return self._data

    @property
    def jump_target(self) -> tuple | None:
        return self._jump_target

    @staticmethod
    def _ease_in_out_quad(t: float) -> float:
        t = max(0.0, min(1.0, t))
        return 2.0 * t * t if t < 0.5 else 1.0 - (-2.0 * t + 2.0) ** 2 / 2.0

    def is_done(self) -> bool:
        return self._pc >= len(self._segments)

    def _get_type(self, seg: tuple) -> str:
        return "POS" if isinstance(seg[0], dict) else seg[0]

    def _eval_src(self, src: str, pad: list | None) -> float:
        btn_idx = _BTN_NAME_TO_PAD_IDX.get(src)
        if btn_idx is not None:
            return float(pad[btn_idx]) if pad is not None else 0.0
        # D-pad (hat) discretes
        if src == "UP":
            return 1.0 if (pad is not None and pad[PAD_HAT_Y] >= 1.0) else 0.0
        if src == "DOWN":
            return 1.0 if (pad is not None and pad[PAD_HAT_Y] <= -1.0) else 0.0
        if src == "LEFT":
            return 1.0 if (pad is not None and pad[PAD_HAT_X] <= -1.0) else 0.0
        if src == "RIGHT":
            return 1.0 if (pad is not None and pad[PAD_HAT_X] >= 1.0) else 0.0
        # L2/R2 button = analog trigger past BTN_THRESH
        if src == "L2":
            return 1.0 if (pad is not None and pad[PAD_AXIS_L2V] > BTN_THRESH) else 0.0
        if src == "R2":
            return 1.0 if (pad is not None and pad[PAD_AXIS_R2V] > BTN_THRESH) else 0.0
        # Sticks & analog triggers (raw values)
        if src == "LX":  return float(pad[PAD_AXIS_LX])  if pad is not None else 0.0
        if src == "LY":  return float(pad[PAD_AXIS_LY])  if pad is not None else 0.0
        if src == "RX":  return float(pad[PAD_AXIS_RX])  if pad is not None else 0.0
        if src == "RY":  return float(pad[PAD_AXIS_RY])  if pad is not None else 0.0
        if src == "L2V": return float(pad[PAD_AXIS_L2V]) if pad is not None else 0.0
        if src == "R2V": return float(pad[PAD_AXIS_R2V]) if pad is not None else 0.0
        return self._variables.get(src, 0.0)

    def _eval_cmp(self, src: str, op: str, value: float, pad: list | None) -> bool:
        v = self._eval_src(src, pad)
        if op == "HELD":  return v >= BTN_THRESH
        if op == "EQ":    return v == value
        if op == "NE":    return v != value
        if op == "GT":    return v >  value
        if op == "GE":    return v >= value
        if op == "LT":    return v <  value
        if op == "LE":    return v <= value
        if op == "BIT":   return (int(v) & int(value)) != 0
        if op == "NBIT":  return (int(v) & int(value)) == 0
        return False

    def _apply_set(self, var: str, op: str, value: float) -> None:
        cur = self._variables.get(var, 0.0)
        if   op == "MOV": self._variables[var] = float(value)
        elif op == "ADD": self._variables[var] = cur + value
        elif op == "SUB": self._variables[var] = cur - value
        elif op == "MUL": self._variables[var] = cur * value
        elif op == "DIV":
            if value != 0: self._variables[var] = cur / value

    def _jump_to(self, line: int | None) -> None:
        self._pc      = (self._pc + 1) if line is None else line
        self._last_pc = -1

    def advance(self, pad: list | None = None) -> list:
        if self.is_done():
            return self._data

        instant = 0
        while not self.is_done() and instant < _MP_MAX_INSTANT:
            seg   = self._segments[self._pc]
            type_ = self._get_type(seg)

            if type_ == "POS":
                target_joints: dict = seg[0]
                duration_ms: float  = float(seg[1])
                if self._pc != self._last_pc:
                    self._tmr     = 0.0
                    self._next_ms = duration_ms
                    self._last    = {idx: self._data[idx] for idx in target_joints}
                    self._last_pc = self._pc
                # Map easing over N-1 intervals so the last frame naturally reaches target.
                # For single-frame segments (next_ms <= frame_dt), jump straight to t=1.
                _span = self._next_ms - self._frame_dt
                t = min(1.0, self._tmr / _span) if _span > 0 else 1.0
                joint_easing_ = seg[2] if len(seg) > 2 else {}
                # Per-tick angular budget from servo max_speed. Mirrors
                # LME PlaybackController._apply_joint_speed_limits: cur only
                # moves toward ideal by at most v_max*dt per tick, so short
                # POS with impossible Δangle degrade gracefully instead of
                # commanding the physics servo at unreachable rates.
                _dt_sec = self._frame_dt / 1000.0
                for idx, angle_end in target_joints.items():
                    es_t = _apply_easing(joint_easing_.get(idx, 0) if joint_easing_ else 0, t)
                    ideal = self._last[idx] + (angle_end - self._last[idx]) * es_t
                    v_max = JOINT_MAX_SPEED_DEG_S.get(idx, _DEFAULT_MAX_SPEED_DEG_S)
                    max_step = v_max * _dt_sec
                    cur = self._data[idx]
                    delta = ideal - cur
                    if abs(delta) <= max_step:
                        cur = ideal
                    else:
                        cur = cur + (max_step if delta >= 0 else -max_step)
                    self._data[idx]     = cur
                    self._data[idx - 1] = 1.0
                self._tmr += self._frame_dt
                if self._tmr >= self._next_ms:
                    # Do NOT snap _data[idx] to target — servo may not have
                    # reached it within duration. Next segment's _last[idx]
                    # captures actual (speed-limited) position and interpolates
                    # from there. Matches LME playback behavior.
                    self._pc      += 1
                    self._last_pc  = -1
                break

            elif type_ == "CMP":
                if len(seg) == 5:
                    _, src, op, branch_line, next_line = seg; value = None
                else:
                    _, src, op, value, branch_line, next_line = seg
                old_pc = self._pc
                if self._eval_cmp(src, op, value, pad):
                    self._jump_to(branch_line)
                else:
                    self._jump_to(next_line)
                if self._pc == old_pc:
                    break
                instant += 1

            elif type_ == "JUMP":
                if len(seg) == 2:
                    old_pc = self._pc
                    self._jump_to(seg[1])
                    if self._pc == old_pc:
                        break
                    instant += 1
                else:
                    self._jump_target = (seg[1], seg[2])
                    break

            elif type_ == "SET":
                _, var, op, value = seg
                self._apply_set(var, op, value)
                self._pc      += 1
                self._last_pc  = -1
                instant += 1

            elif type_ == "CALL":
                fn_name = seg[1] if len(seg) > 1 else ""
                if fn_name:
                    fn = globals().get(fn_name)
                    if callable(fn):
                        fn()
                    cmdr = globals().get("_bhv_commander")
                    if cmdr is not None:
                        pose = getattr(cmdr, "_pose_data", None)
                        if callable(pose):
                            self._data = list(pose())
                        elif getattr(cmdr, "controller", None) is not None and getattr(cmdr.controller, "data", None):
                            self._data = list(cmdr.controller.data)
                self._pc      += 1
                self._last_pc  = -1
                # One CALL per control tick (matches LME PlaybackController function JumpNodes).
                break

        if instant >= _MP_MAX_INSTANT:
            logger.warning("[MotionPlayer] instant step limit — possible infinite loop")

        return self._data


# ── Commander ─────────────────────────────────────────────────────────────────
class Commander:
    """モーション再生エンジン。コントローラは ProjectCode が任意で供給する。"""

    def __init__(self, loop_hz: int = 100) -> None:
        self._loop_hz     = loop_hz
        self._loop_dt     = 1.0 / loop_hz
        self._frame_budget_ms = self._loop_dt * 1000.0 * 0.85

        self._pad: list | None = None
        self._pad_lock          = threading.Lock()
        self._imu: list         = [0.0] * 90
        self._last_output: list = [0.0] * 90
        self._output_lock       = threading.Lock()
        self._pose              = [0.0] * 90

        self.controller = None
        for _cls_name in ("MotionController", "WalkController", "Controller"):
            _cls = globals().get(_cls_name)
            if isinstance(_cls, type):
                try:
                    self.controller = _cls()
                    break
                except Exception as exc:
                    logger.warning("%s() failed: %s", _cls_name, exc)
        _stop = getattr(self.controller, "stop", None) or getattr(self.controller, "stop_walk", None)
        if callable(_stop):
            _stop()

        self.state                         = STATE_IDLE
        self._prev_state                   = STATE_IDLE
        self._motion: MotionPlayer | None  = None
        self._variables: dict              = {}

    @property
    def walk(self):
        """Alias for .controller (older ProjectCode)."""
        return self.controller

    @walk.setter
    def walk(self, value):
        self.controller = value

    def set_pad(self, pad: list) -> None:
        with self._pad_lock:
            self._pad = list(pad)

    def set_imu(self, r: list) -> None:
        self._imu = list(r)

    def get_last_output(self) -> list:
        with self._output_lock:
            return list(self._last_output)

    def _pose_data(self) -> list:
        c = self.controller
        data = getattr(c, "data", None) if c is not None else None
        if isinstance(data, list) and data:
            return data
        return self._pose

    def _publish(self, data: list) -> None:
        out_mrd = list(data)
        for i in range(21, 81, 2):
            out_mrd[i] = round(float(out_mrd[i]) * 100.0, 2)
        with self._output_lock:
            self._last_output = out_mrd

    def _resolve_motion(self, motion_ref) -> list | None:
        if motion_ref is None:
            return None
        if isinstance(motion_ref, list):
            return motion_ref
        if isinstance(motion_ref, str):
            obj = globals().get(motion_ref)
            return obj if isinstance(obj, list) else None
        return None

    def _trigger_motion(self, segments: list, label: str) -> None:
        if self.state != STATE_MOTION:
            self._prev_state = self.state
        self.state   = STATE_MOTION
        self._motion = MotionPlayer(segments, list(self._pose_data()),
                                    loop_hz=self._loop_hz, variables=self._variables)
        logger.info(f"[CMD] → {label}")

    def poll_and_update(self) -> None:
        """Drive Boot/Base MOTION lists only. Stick/buttons are CMP inside Base."""
        with self._pad_lock:
            pad = list(self._pad) if self._pad is not None else None

        if self.state == STATE_MOTION and self._motion is not None and not self._motion.is_done():
            self._publish(self._motion.advance(pad=pad))
            jt = self._motion.jump_target
            if jt is not None:
                target_segs = self._resolve_motion(jt[0])
                start_line  = int(jt[1]) if jt[1] is not None else 0
                if target_segs is not None:
                    self._motion = MotionPlayer(
                        target_segs, self._motion.data,
                        loop_hz=self._loop_hz, variables=self._variables,
                        start_line=start_line,
                    )
                    logger.info(f"[CMD] → JUMP {jt[0]!r}:{start_line}")
                else:
                    logger.warning(f"[CMD] JUMP: unknown motion {jt[0]!r}")
                    self._motion = None
                    self._return_to_base(pad)
            return

        # Motion finished or never started → Base wait loop (not analog hijack).
        self._return_to_base(pad)

    def _return_to_base(self, pad: list | None) -> None:
        base = globals().get("MOTION_BASE")
        if isinstance(base, list) and base:
            _stop = getattr(self.controller, "stop", None) or getattr(self.controller, "stop_walk", None)
            if callable(_stop):
                _stop()
            self._trigger_motion(base, "Base")
            if self._motion is not None:
                self._publish(self._motion.advance(pad=pad))
            return
        self.state = STATE_IDLE
        self._motion = None
        self._publish(self._pose_data())


# ── BHV system functions ──────────────────────────────────────────────────────
_bhv_commander:        Commander | None = None
_bhv_user_logic_fn                      = None
_bhv_frame_count:      int              = 0
_bhv_frame_budget_ms:  float            = 8.5


def bhv_setup(user_setup_fn, user_logic_fn,
              loop_hz: int = 100) -> None:
    """BHVスタート時に1回呼ぶ。Commander を初期化して user_setup_fn を実行する。"""
    global _bhv_commander, _bhv_user_logic_fn, _bhv_frame_budget_ms
    _bhv_frame_budget_ms = (1.0 / loop_hz) * 1000.0 * 0.85
    _bhv_commander = Commander(loop_hz=loop_hz)
    _bhv_user_logic_fn = user_logic_fn
    user_setup_fn()
    logger.info(f"BHV ready  loop_hz={loop_hz}  budget={_bhv_frame_budget_ms:.1f}ms/frame")


def bhv_update(r: list, s: list) -> list:
    """毎フレーム呼ぶ。user_logic を実行し Late 検出を行う。"""
    global _bhv_frame_count
    if _bhv_commander is None or _bhv_user_logic_fn is None:
        return s
    if len(r) < 19 or len(s) <= 18:
        return s
    _bhv_frame_count += 1
    t0     = time.perf_counter()
    result = _bhv_user_logic_fn(r, s)
    elapsed_ms = (time.perf_counter() - t0) * 1000.0
    if elapsed_ms > _bhv_frame_budget_ms:
        logger.warning(f"[LATE] frame={_bhv_frame_count}  elapsed={elapsed_ms:.1f}ms"
                       f"  budget={_bhv_frame_budget_ms:.1f}ms")
    return result if result is not None else s


def run_default(r: list, s: list) -> list:
    """Feed pad/IMU into Commander. Boot/Base MOTION lists drive all input.
    user_logic() の中で return run_default(r, s) と書くだけで使える。
    """
    if _bhv_commander is None:
        return s
    _bhv_commander.set_imu(r)
    _bhv_commander.set_pad(_decode_meridim_pad(s))
    _bhv_commander.poll_and_update()
    return _bhv_commander.get_last_output()


# ════════════════════════════════════════════════════════════════════════════
# BHV interface (do not modify)
# ════════════════════════════════════════════════════════════════════════════
def setup():         bhv_setup(user_setup, user_logic, loop_hz=LOOP_HZ)
def update(r, s):    return bhv_update(r, s)


# ════════════════════════════════════════════════════════════════════════════
# ★★★  USER WORK AREA  ★★★  (regenerated on every export)
# ════════════════════════════════════════════════════════════════════════════

LOOP_HZ = 100

# Forward declarations for cross-motion JUMP references.
MOTION_BOOT: list = []
MOTION_BASE: list = []
MOTION_WALK_FORWARD: list = []
MOTION_WALK_BACK: list = []
MOTION_WALK_SIDESTEP_LEFT: list = []
MOTION_WALK_SIDESTEP_RIGHT: list = []
MOTION_WALK_TURN_LEFT_SMALL: list = []
MOTION_WALK_TURN_RIGHT_SMALL: list = []
MOTION_STANDUP_FACE_UP: list = []
MOTION_STANDUP_FACE_UPDOWN: list = []
MOTION_DEFENCE_DUCKING: list = []
MOTION_ATTACK_JAB1_L: list = []
MOTION_ATTACK_JAB1_R: list = []
MOTION_ATACK_STRAIGHT_L: list = []
MOTION_ATACK_STRAIGHT_R: list = []
MOTION_HELLO: list = []

MOTION_BOOT.extend([  # Boot
    ({23: 0.0, 25: 0.0, 27: 0.0, 29: 0.0, 33: 0.0, 35: 0.0, 37: 0.0, 39: 0.0, 41: 0.0, 21: 0.0, 53: 0.0, 55: -0.0, 57: -0.0, 59: 0.0, 63: -0.0, 65: 0.0, 67: 0.0, 69: 0.0, 71: -0.0, 51: 0.0}, 100, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0, 51: 0}),  # line 0
    ({23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 21: 0.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0, 51: 0.0}, 1000, {23: 3, 25: 3, 27: 3, 29: 3, 33: 3, 35: 3, 37: 3, 39: 3, 41: 3, 21: 3, 53: 3, 55: 3, 57: 3, 59: 3, 63: 3, 65: 3, 67: 3, 69: 3, 71: 3, 51: 3}),  # line 1
    ({23: 20.0, 25: 0.0, 27: 0.0, 29: -100.0, 33: 0.0, 35: -32.2, 37: 64.4, 39: -32.2, 41: 0.0, 21: 0.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -100.0, 63: -0.0, 65: -32.2, 67: 64.4, 69: -32.2, 71: -0.0, 51: 0.0}, 100, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0, 51: 0}),  # line 2
    ('JUMP', MOTION_BASE, 0),  # line 3
])

MOTION_BASE.extend([  # Base
    ('CMP', 'UP', 'HELD', 1, 3),  # line 0
    ('JUMP', MOTION_STANDUP_FACE_UP, 0),  # line 1
    ('JUMP', 47),  # line 2
    ('CMP', 'DOWN', 'HELD', 4, 6),  # line 3
    ('JUMP', MOTION_STANDUP_FACE_UPDOWN, 0),  # line 4
    ('JUMP', 47),  # line 5
    ('CMP', 'LY', 'LE', -0.11811023622047244, 7, 9),  # line 6
    ('JUMP', MOTION_WALK_FORWARD, 0),  # line 7
    ('JUMP', 47),  # line 8
    ('CMP', 'LY', 'GE', 0.11811023622047244, 10, 12),  # line 9
    ('JUMP', MOTION_WALK_BACK, 0),  # line 10
    ('JUMP', 47),  # line 11
    ('CMP', 'LX', 'GE', 0.11811023622047244, 13, 15),  # line 12
    ('JUMP', MOTION_WALK_SIDESTEP_RIGHT, 0),  # line 13
    ('JUMP', 47),  # line 14
    ('CMP', 'LX', 'LE', -0.11811023622047244, 16, 18),  # line 15
    ('JUMP', MOTION_WALK_SIDESTEP_LEFT, 0),  # line 16
    ('JUMP', 47),  # line 17
    ('CMP', 'RX', 'GE', 0.14960629921259844, 19, 21),  # line 18
    ('JUMP', MOTION_WALK_TURN_RIGHT_SMALL, 0),  # line 19
    ('JUMP', 47),  # line 20
    ('CMP', 'RX', 'LE', -0.14960629921259844, 22, 24),  # line 21
    ('JUMP', MOTION_WALK_TURN_LEFT_SMALL, 0),  # line 22
    ('JUMP', 47),  # line 23
    ('CMP', 'R1', 'HELD', 25, 27),  # line 24
    ('JUMP', MOTION_ATTACK_JAB1_R, 0),  # line 25
    ('JUMP', 47),  # line 26
    ('CMP', 'L1', 'HELD', 28, 30),  # line 27
    ('JUMP', MOTION_ATTACK_JAB1_L, 0),  # line 28
    ('JUMP', 47),  # line 29
    ('CMP', 'L2', 'HELD', 31, 33),  # line 30
    ('JUMP', MOTION_ATACK_STRAIGHT_L, 0),  # line 31
    ('JUMP', 47),  # line 32
    ('CMP', 'R2', 'HELD', 34, 36),  # line 33
    ('JUMP', MOTION_ATACK_STRAIGHT_R, 0),  # line 34
    ('JUMP', 47),  # line 35
    ('CMP', 'CRS', 'HELD', 37, 39),  # line 36
    ('JUMP', MOTION_DEFENCE_DUCKING, 0),  # line 37
    ('JUMP', 47),  # line 38
    ('CMP', 'CRS', 'HELD', 40, 42),  # line 39
    ('JUMP', MOTION_DEFENCE_DUCKING, 0),  # line 40
    ('JUMP', 47),  # line 41
    ('CMP', 'CIR', 'HELD', 43, 45),  # line 42
    ('JUMP', MOTION_HELLO, 0),  # line 43
    ('JUMP', 47),  # line 44
    ({}, 10),  # line 45
    ('JUMP', 0),  # line 46
])

MOTION_WALK_FORWARD.extend([  # walk_forward
    ('CMP', 'LY', 'LE', -0.11811023622047244, 1, 4),  # line 0
    ('CALL', 'walk_ik_step'),  # line 1
    ('JUMP', 0),  # line 2
    ('JUMP', 6),  # line 3
    ({51: 0.0, 21: 0.0, 23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 100, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 4
    ('JUMP', MOTION_BASE, 6),  # line 5
])

MOTION_WALK_BACK.extend([  # walk_back
    ('CMP', 'LY', 'GE', 0.11811023622047244, 1, 4),  # line 0
    ('CALL', 'walk_ik_step'),  # line 1
    ('JUMP', 0),  # line 2
    ('JUMP', 6),  # line 3
    ({51: 0.0, 21: 0.0, 23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 100, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 4
    ('JUMP', MOTION_BASE, 6),  # line 5
])

MOTION_WALK_SIDESTEP_LEFT.extend([  # walk_sidestep_left
    ('CMP', 'LX', 'LE', -0.11811023622047244, 1, 4),  # line 0
    ('CALL', 'walk_ik_step'),  # line 1
    ('JUMP', 0),  # line 2
    ('JUMP', 6),  # line 3
    ({51: 0.0, 21: 0.0, 23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 100, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 4
    ('JUMP', MOTION_BASE, 6),  # line 5
])

MOTION_WALK_SIDESTEP_RIGHT.extend([  # walk_sidestep_right
    ('CMP', 'LX', 'GE', 0.11811023622047244, 1, 4),  # line 0
    ('CALL', 'walk_ik_step'),  # line 1
    ('JUMP', 0),  # line 2
    ('JUMP', 6),  # line 3
    ({51: 0.0, 21: 0.0, 23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 100, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 4
    ('JUMP', MOTION_BASE, 6),  # line 5
])

MOTION_WALK_TURN_LEFT_SMALL.extend([  # walk_turn_left_small
    ('CMP', 'RX', 'LE', -0.11811023622047244, 1, 4),  # line 0
    ('CALL', 'walk_ik_step'),  # line 1
    ('JUMP', 0),  # line 2
    ('JUMP', 6),  # line 3
    ({51: 0.0, 21: 0.0, 23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 100, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 4
    ('JUMP', MOTION_BASE, 6),  # line 5
])

MOTION_WALK_TURN_RIGHT_SMALL.extend([  # walk_turn_right_small
    ('CMP', 'RX', 'GE', 0.11811023622047244, 1, 4),  # line 0
    ('CALL', 'walk_ik_step'),  # line 1
    ('JUMP', 0),  # line 2
    ('JUMP', 6),  # line 3
    ({51: 0.0, 21: 0.0, 23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 100, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 4
    ('JUMP', MOTION_BASE, 6),  # line 5
])

MOTION_STANDUP_FACE_UP.extend([  # standup_face_up
    ({51: 0.0, 21: 0.0, 23: 0.0, 25: 0.0, 27: 0.0, 29: 0.0, 53: 0.0, 55: -0.0, 57: -0.0, 59: 0.0, 33: 0.0, 35: 0.0, 37: 0.0, 39: -22.0, 41: 0.0, 63: -0.0, 65: 0.0, 67: 0.0, 69: -22.0, 71: -0.0}, 100, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 0
    ({23: 90.0, 25: 0.0, 27: 0.0, 29: -100.0, 33: 0.0, 35: -50.0, 37: 110.0, 39: 0.0, 41: 0.0, 51: 0.0, 21: 0.0, 53: 90.0, 55: -0.0, 57: -0.0, 59: -100.0, 63: -0.0, 65: -50.0, 67: 110.0, 69: 0.0, 71: -0.0}, 500, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 1
    ({23: 90.0, 25: 0.0, 27: 0.0, 29: -33.0, 33: 0.0, 35: 52.0, 37: 110.0, 39: -100.0, 41: 0.0, 51: 0.0, 21: 0.0, 53: 90.0, 55: -0.0, 57: -0.0, 59: -33.0, 63: -0.0, 65: 52.0, 67: 110.0, 69: -100.0, 71: -0.0}, 500, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 2
    ({23: 90.0, 25: 0.0, 27: 0.0, 29: 0.0, 33: 0.0, 35: 52.0, 37: 110.0, 39: -100.0, 41: 0.0, 51: 0.0, 21: 0.0, 53: 90.0, 55: -0.0, 57: -0.0, 59: 0.0, 63: -0.0, 65: 52.0, 67: 110.0, 69: -100.0, 71: -0.0}, 500, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 3
    ({23: 50.0, 25: 10.0, 27: 0.0, 29: 0.0, 33: 0.0, 35: 70.0, 37: 70.0, 39: -100.0, 41: 0.0, 51: 0.0, 21: 0.0, 53: 50.0, 55: 10.0, 57: -0.0, 59: 0.0, 63: -0.0, 65: 70.0, 67: 70.0, 69: -100.0, 71: -0.0}, 500, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 4
    ({23: 50.0, 25: 10.0, 27: 0.0, 29: 0.0, 33: 0.0, 35: 30.0, 37: 70.0, 39: -70.0, 41: 0.0, 51: 0.0, 21: 0.0, 53: 50.0, 55: 10.0, 57: -0.0, 59: 0.0, 63: -0.0, 65: 30.0, 67: 70.0, 69: -70.0, 71: -0.0}, 500, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 5
    ({23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 51: 0.0, 21: 0.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 1000, {23: 3, 25: 3, 27: 3, 29: 3, 33: 3, 35: 3, 37: 3, 39: 3, 41: 3, 51: 3, 21: 3, 53: 3, 55: 3, 57: 3, 59: 3, 63: 3, 65: 3, 67: 3, 69: 3, 71: 3}),  # line 6
    ('JUMP', MOTION_BASE, 0),  # line 7
])

MOTION_STANDUP_FACE_UPDOWN.extend([  # standup_face_updown
    ({51: 0.0, 21: 0.0, 23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 100, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 0
    ({51: 0.0, 21: 0.0, 23: 0.0, 25: 180.0, 27: 0.0, 29: 0.0, 53: 0.0, 55: 180.0, 57: -0.0, 59: 0.0, 33: 90.0, 35: -60.0, 37: 120.0, 39: -60.0, 41: -40.0, 63: 90.0, 65: -60.0, 67: 120.0, 69: -60.0, 71: -40.0}, 500, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 1
    ({51: -90.0, 21: 0.0, 23: 0.0, 25: 180.0, 27: 0.0, 29: 0.0, 53: 0.0, 55: 180.0, 57: -0.0, 59: 0.0, 33: 90.0, 35: -60.0, 37: 120.0, 39: -60.0, 41: -40.0, 63: 90.0, 65: -60.0, 67: 120.0, 69: -60.0, 71: -40.0}, 200, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 2
    ({51: -90.0, 21: 0.0, 23: 0.0, 25: 180.0, 27: 0.0, 29: 0.0, 53: 0.0, 55: 180.0, 57: -0.0, 59: 0.0, 33: 90.0, 35: -60.0, 37: 120.0, 39: -60.0, 41: -40.0, 63: 90.0, 65: -60.0, 67: 120.0, 69: -60.0, 71: -40.0}, 100, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 3
    ({51: -90.0, 21: 0.0, 23: 0.0, 25: 40.0, 27: 0.0, 29: 0.0, 53: 0.0, 55: 40.0, 57: -0.0, 59: 0.0, 33: 90.0, 35: -60.0, 37: 120.0, 39: -60.0, 41: -40.0, 63: 90.0, 65: -60.0, 67: 120.0, 69: -60.0, 71: -40.0}, 300, {51: 3, 21: 3, 23: 3, 25: 3, 27: 3, 29: 3, 53: 3, 55: 3, 57: 3, 59: 3, 33: 3, 35: 3, 37: 3, 39: 3, 41: 3, 63: 3, 65: 3, 67: 3, 69: 3, 71: 3}),  # line 4
    ({51: -90.0, 21: 0.0, 23: 0.0, 25: 40.0, 27: 0.0, 29: 0.0, 53: 0.0, 55: 40.0, 57: -0.0, 59: 0.0, 33: 90.0, 35: -60.0, 37: 120.0, 39: -60.0, 41: -40.0, 63: 90.0, 65: -60.0, 67: 120.0, 69: -60.0, 71: -40.0}, 500, {51: 3, 21: 3, 23: 3, 25: 3, 27: 3, 29: 3, 53: 3, 55: 3, 57: 3, 59: 3, 33: 3, 35: 3, 37: 3, 39: 3, 41: 3, 63: 3, 65: 3, 67: 3, 69: 3, 71: 3}),  # line 5
    ({51: 0.0, 21: 0.0, 23: 0.0, 25: 40.0, 27: 0.0, 29: -90.0, 53: 0.0, 55: 40.0, 57: -0.0, 59: -90.0, 33: 40.0, 35: -60.0, 37: 120.0, 39: -60.0, 41: -40.0, 63: 40.0, 65: -60.0, 67: 120.0, 69: -60.0, 71: -40.0}, 500, {51: 3, 21: 3, 23: 3, 25: 3, 27: 3, 29: 3, 53: 3, 55: 3, 57: 3, 59: 3, 33: 3, 35: 3, 37: 3, 39: 3, 41: 3, 63: 3, 65: 3, 67: 3, 69: 3, 71: 3}),  # line 6
    ({51: 0.0, 21: 0.0, 23: 0.0, 25: 40.0, 27: 0.0, 29: -90.0, 53: 0.0, 55: 40.0, 57: -0.0, 59: -90.0, 33: 0.0, 35: -60.0, 37: 120.0, 39: -60.0, 41: 0.0, 63: -0.0, 65: -60.0, 67: 120.0, 69: -60.0, 71: -0.0}, 200, {51: 3, 21: 3, 23: 3, 25: 3, 27: 3, 29: 3, 53: 3, 55: 3, 57: 3, 59: 3, 33: 3, 35: 3, 37: 3, 39: 3, 41: 3, 63: 3, 65: 3, 67: 3, 69: 3, 71: 3}),  # line 7
    ({51: 0.0, 21: 0.0, 23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 500, {51: 3, 21: 3, 23: 3, 25: 3, 27: 3, 29: 3, 53: 3, 55: 3, 57: 3, 59: 3, 33: 3, 35: 3, 37: 3, 39: 3, 41: 3, 63: 3, 65: 3, 67: 3, 69: 3, 71: 3}),  # line 8
    ({51: 0.0, 21: 0.0, 23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 100, {51: 3, 21: 3, 23: 3, 25: 3, 27: 3, 29: 3, 53: 3, 55: 3, 57: 3, 59: 3, 33: 3, 35: 3, 37: 3, 39: 3, 41: 3, 63: 3, 65: 3, 67: 3, 69: 3, 71: 3}),  # line 9
    ('JUMP', MOTION_BASE, 0),  # line 10
])

MOTION_DEFENCE_DUCKING.extend([  # Defence_Ducking
    ({51: 0.0, 21: 0.0, 23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 100, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 0
    ({51: 0.0, 21: 0.0, 23: 20.0, 25: 30.0, 27: 0.0, 29: -90.0, 53: 20.0, 55: 30.0, 57: -0.0, 59: -90.0, 33: 30.0, 35: -40.0, 37: 80.0, 39: -40.0, 41: -30.0, 63: 30.0, 65: -40.0, 67: 80.0, 69: -40.0, 71: -30.0}, 100, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 1
    ('CMP', 'CRS', 'HELD', 3, 6),  # line 2
    ({51: 0.0, 21: 0.0, 23: 20.0, 25: 30.0, 27: 0.0, 29: -90.0, 53: 20.0, 55: 30.0, 57: -0.0, 59: -90.0, 33: 30.0, 35: -40.0, 37: 80.0, 39: -40.0, 41: -30.0, 63: 30.0, 65: -40.0, 67: 80.0, 69: -40.0, 71: -30.0}, 100, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 3
    ('JUMP', 1),  # line 4
    ('JUMP', 8),  # line 5
    ({51: 0.0, 21: 0.0, 23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 100, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 6
    ('JUMP', MOTION_BASE, 0),  # line 7
])

MOTION_ATTACK_JAB1_L.extend([  # Attack_jab1_l
    ({51: -20.0, 21: 20.0, 23: -90.0, 25: 0.0, 27: -30.0, 29: 0.0, 53: 20.0, 55: 10.0, 57: -0.0, 59: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 300, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 0
    ('CMP', 'L1', 'HELD', 2, 5),  # line 1
    ({51: -20.0, 21: 20.0, 23: -120.0, 25: 0.0, 27: -30.0, 29: -60.0, 53: 20.0, 55: 10.0, 57: -0.0, 59: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 50, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 2
    ('JUMP', 1),  # line 3
    ('JUMP', 7),  # line 4
    ({23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 51: 0.0, 21: 0.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 350, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 5
    ('JUMP', MOTION_BASE, 0),  # line 6
])

MOTION_ATTACK_JAB1_R.extend([  # Attack_jab1_r
    ({23: 20.0, 25: 10.0, 27: 0.0, 29: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 51: 20.0, 21: -20.0, 53: -90.0, 55: -0.0, 57: -30.0, 59: 0.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 300, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 0
    ('CMP', 'R1', 'HELD', 2, 5),  # line 1
    ({23: 20.0, 25: 10.0, 27: 0.0, 29: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 51: 20.0, 21: -20.0, 53: -120.0, 55: -0.0, 57: -30.0, 59: -60.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 50, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 2
    ('JUMP', 1),  # line 3
    ('JUMP', 7),  # line 4
    ({23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 51: 0.0, 21: 0.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 350, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 5
    ('JUMP', MOTION_BASE, 0),  # line 6
])

MOTION_ATACK_STRAIGHT_L.extend([  # Atack_straight_l
    ({23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 51: 0.0, 21: 0.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 100, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 0
    ({23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 33: -12.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 12.0, 51: 0.0, 21: 0.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 63: 14.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -12.0}, 100, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 1
    ({23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 33: -12.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 12.0, 51: 0.0, 21: 0.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 63: 14.0, 65: -60.0, 67: 90.0, 69: -30.0, 71: -12.0}, 100, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 2
    ({23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 33: 0.0, 35: 0.0, 37: 60.0, 39: -60.0, 41: 0.0, 51: 0.0, 21: 0.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 63: -0.0, 65: -60.0, 67: 60.0, 69: 0.0, 71: -0.0}, 100, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 3
    ({51: -45.0, 21: 45.0, 23: 0.0, 25: 45.0, 27: 0.0, 29: -45.0, 53: 20.0, 55: 45.0, 57: -0.0, 59: -90.0, 33: 0.0, 35: 0.0, 37: 60.0, 39: -60.0, 41: 0.0, 63: -0.0, 65: -60.0, 67: 60.0, 69: 0.0, 71: -0.0}, 100, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 4
    ({23: 0.0, 25: 80.0, 27: 0.0, 29: 0.0, 33: 0.0, 35: 0.0, 37: 60.0, 39: -60.0, 41: 0.0, 51: -80.0, 21: 60.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 63: -0.0, 65: -60.0, 67: 60.0, 69: 0.0, 71: -0.0}, 200, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 5
    ({23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 51: 0.0, 21: 0.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 100, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 6
    ({51: 0.0, 21: 0.0, 23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 500, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 7
    ('JUMP', MOTION_BASE, 0),  # line 8
])

MOTION_ATACK_STRAIGHT_R.extend([  # Atack_straight_r
    ({23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 51: 0.0, 21: 0.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 100, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 0
    ({23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 33: 14.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: -12.0, 51: 0.0, 21: 0.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 63: -12.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: 12.0}, 100, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 1
    ({23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 33: 14.0, 35: -60.0, 37: 90.0, 39: -30.0, 41: -12.0, 51: 0.0, 21: 0.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 63: -12.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: 12.0}, 100, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 2
    ({23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 33: 0.0, 35: -60.0, 37: 60.0, 39: 0.0, 41: 0.0, 51: 0.0, 21: 0.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 63: -0.0, 65: 0.0, 67: 60.0, 69: -60.0, 71: -0.0}, 100, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 3
    ({23: 20.0, 25: 45.0, 27: 0.0, 29: -90.0, 33: 0.0, 35: -60.0, 37: 60.0, 39: 0.0, 41: 0.0, 51: 45.0, 21: -45.0, 53: 0.0, 55: 45.0, 57: -0.0, 59: -45.0, 63: -0.0, 65: 0.0, 67: 60.0, 69: -60.0, 71: -0.0}, 100, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 4
    ({23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 33: 0.0, 35: -60.0, 37: 60.0, 39: 0.0, 41: 0.0, 51: 80.0, 21: -60.0, 53: 0.0, 55: 80.0, 57: -0.0, 59: 0.0, 63: -0.0, 65: 0.0, 67: 60.0, 69: -60.0, 71: -0.0}, 200, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 5
    ({23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 51: 0.0, 21: 0.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 100, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 6
    ({23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 51: 0.0, 21: 0.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 500, {23: 0, 25: 0, 27: 0, 29: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 51: 0, 21: 0, 53: 0, 55: 0, 57: 0, 59: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 7
    ('JUMP', MOTION_BASE, 0),  # line 8
])

MOTION_HELLO.extend([  # Hello
    ({51: 0.0, 21: 0.0, 23: 10.0, 25: 0.0, 27: 0.0, 29: -10.0, 53: 10.0, 55: -0.0, 57: -0.0, 59: -10.0, 33: 0.0, 35: 0.0, 37: 0.0, 39: 0.0, 41: 0.0, 63: -0.0, 65: 0.0, 67: 0.0, 69: 0.0, 71: -0.0}, 350, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 0
    ({51: 0.0, 21: 0.0, 23: 10.0, 25: 0.0, 27: 0.0, 29: -10.0, 53: 10.0, 55: -0.0, 57: -0.0, 59: -10.0, 33: 0.0, 35: 0.0, 37: 0.0, 39: 0.0, 41: 0.0, 63: -0.0, 65: 0.0, 67: 0.0, 69: 0.0, 71: -0.0}, 200, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 1
    ({51: 0.0, 21: 0.0, 23: 20.0, 25: 0.0, 27: 0.0, 29: -10.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -10.0, 33: 0.0, 35: -20.0, 37: 0.0, 39: 0.0, 41: 0.0, 63: -0.0, 65: -20.0, 67: 0.0, 69: 0.0, 71: -0.0}, 1000, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 2
    ({51: 0.0, 21: 0.0, 23: 20.0, 25: 0.0, 27: 0.0, 29: -10.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -10.0, 33: 0.0, 35: -20.0, 37: 0.0, 39: 0.0, 41: 0.0, 63: -0.0, 65: -20.0, 67: 0.0, 69: 0.0, 71: -0.0}, 500, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 3
    ({51: 0.0, 21: 0.0, 23: 10.0, 25: 0.0, 27: 0.0, 29: -10.0, 53: 10.0, 55: -0.0, 57: -0.0, 59: -10.0, 33: 0.0, 35: 0.0, 37: 0.0, 39: 0.0, 41: 0.0, 63: -0.0, 65: 0.0, 67: 0.0, 69: 0.0, 71: -0.0}, 1000, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 4
    ({51: 0.0, 21: 0.0, 23: 10.0, 25: 0.0, 27: 0.0, 29: -10.0, 53: 10.0, 55: -0.0, 57: -0.0, 59: -10.0, 33: 0.0, 35: 0.0, 37: 0.0, 39: 0.0, 41: 0.0, 63: -0.0, 65: 0.0, 67: 0.0, 69: 0.0, 71: -0.0}, 1000, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 5
    ({51: 0.0, 21: 0.0, 23: 20.0, 25: 0.0, 27: 0.0, 29: -90.0, 53: 20.0, 55: -0.0, 57: -0.0, 59: -90.0, 33: 0.0, 35: -30.0, 37: 60.0, 39: -30.0, 41: 0.0, 63: -0.0, 65: -30.0, 67: 60.0, 69: -30.0, 71: -0.0}, 350, {51: 0, 21: 0, 23: 0, 25: 0, 27: 0, 29: 0, 53: 0, 55: 0, 57: 0, 59: 0, 33: 0, 35: 0, 37: 0, 39: 0, 41: 0, 63: 0, 65: 0, 67: 0, 69: 0, 71: 0}),  # line 6
    ('JUMP', MOTION_BASE, 0),  # line 7
])

# ────────────────────────────────────────────────────────────────────────────
# ── User Code (from LME Code editor) ────────────────────────────────────────
# ────────────────────────────────────────────────────────────────────────────

from dataclasses import dataclass, field

# Melissa歩行パラメータ。外部walkparam.jsonには依存せず、LMEプロジェクト内で完結させる。
WALK_PARAMS = {
    'frame_interval': 0.010,
    'phase_offset': 3.141592653589793,
    'init_wait_time': 0.0,
    'landing_period_ratio': 0.10,
    'weight_shift_duration_ratio': 0.25,
    'end_of_simulation': 8.0,
    'cycle_duration': 0.40,
    'swing_ratio': 0.4,
    'foot_lift': 0.015,
    'hip_swing': 0.010,
    'lateral_swing_ratio_1st': 0.8,
    'forward_stride': 0.018,
    'duration': 5.0,
    'forward_lean_angle': 0.0,
    'shoulder_roll_angle': 10.0,
    'arm_swing_angle': 20.0,
    'smooth_stop': False,
    'mix_enable': False,
    'mix_gyro_g': 0.001,
    'term_foot_land': 0.18,
    'term_foot_weight_shift': 0.45,
    'term_land_stride': 0.18,
    'foot_stride_max': 0.018,
    'foot_side_max': 0.025,
}

# melissa_mjcf.xmlのbody posから算出した実リンク長。
LINK_PARAMS = {
    'THIGH_LENGTH': 0.05961695,
    'SHANK_LENGTH': 0.05999871,
    'ANKLE_LENGTH': 0.0,
    'ANKLE_TO_FOOT': 0.036,
    'SHORTEN_LEG_LENGTH': 0.01840,
}

STICK_DEAD = 0.12
SIDE_STICK_THRESH = 90 / 127.0
TURN_STICK_DEAD = 0.15
FOOT_SLIDE_MAX_FWD = 0.070
WALK_STRIDE_RATIO = 0.50
MAX_FWD_STRIDE = FOOT_SLIDE_MAX_FWD * WALK_STRIDE_RATIO
MAX_TURN_STRIDE_DEG = 30.0
MAX_ARM_PITCH_DEG = 15.0

IDX_L_SHOULDER_PITCH = 23
IDX_L_SHOULDER_ROLL = 25
IDX_L_ELBOW_YAW = 27
IDX_L_ELBOW_PITCH = 29
IDX_C_HEAD = 21
IDX_C_CHEST = 51
IDX_R_SHOULDER_PITCH = 53
IDX_R_SHOULDER_ROLL = 55
IDX_R_ELBOW_YAW = 57
IDX_R_ELBOW_PITCH = 59
IDX_L_HIP_ROLL = 33
IDX_L_HIP_PITCH = 35
IDX_L_KNEE = 37
IDX_L_ANKLE_P = 39
IDX_L_ANKLE_ROLL = 41
IDX_R_HIP_ROLL = 63
IDX_R_HIP_PITCH = 65
IDX_R_KNEE = 67
IDX_R_ANKLE_P = 69
IDX_R_ANKLE_ROLL = 71
MELISSA_LEFT_LEG_INDICES = (
    IDX_L_HIP_ROLL, IDX_L_HIP_PITCH, IDX_L_KNEE, IDX_L_ANKLE_P, IDX_L_ANKLE_ROLL,
)
MELISSA_RIGHT_LEG_INDICES = (
    IDX_R_HIP_ROLL, IDX_R_HIP_PITCH, IDX_R_KNEE, IDX_R_ANKLE_P, IDX_R_ANKLE_ROLL,
)
MELISSA_SERVO_INDICES = (
    IDX_C_HEAD,
    IDX_L_SHOULDER_PITCH, IDX_L_SHOULDER_ROLL, IDX_L_ELBOW_YAW, IDX_L_ELBOW_PITCH,
    *MELISSA_LEFT_LEG_INDICES,
    IDX_C_CHEST,
    IDX_R_SHOULDER_PITCH, IDX_R_SHOULDER_ROLL, IDX_R_ELBOW_YAW, IDX_R_ELBOW_PITCH,
    *MELISSA_RIGHT_LEG_INDICES,
)


def _param_field(default, description, type_):
    return field(default=default, metadata={'description': description, 'type': type_})

@dataclass
class WalkParams:
    frame_interval: float            = _param_field(0.010, "1フレームあたりの時間間隔（固定）[秒]", "float")
    phase_offset: float              = _param_field(math.pi, "左右の足の位相差[rad]", "float")
    init_wait_time: float            = _param_field(0.0,  "初期待機時間[秒]", "float")
    landing_period_ratio: float      = _param_field(0.10, "両足着地期間の比率", "float")
    weight_shift_duration_ratio: float = _param_field(0.25, "重心移動期間の比率", "float")
    end_of_simulation: float         = _param_field(8.0,  "シミュレーション終了時間[秒]", "float")
    cycle_duration: float            = _param_field(0.6,  "左右の軸足交代2回分の周期[秒]", "float")
    swing_ratio: float               = _param_field(0.4,  "遊脚期間の比率 (0.0-1.0、推奨0.4)", "float")
    foot_lift: float                 = _param_field(0.020, "遊脚の持ち上げ量[m]", "float")
    hip_swing: float                 = _param_field(0.015, "横方向のスイング量[m]", "float")
    lateral_swing_ratio_1st: float   = _param_field(0.8,  "初期の重心移動時の横スイング倍率", "float")
    forward_stride: float            = _param_field(0.02, "前後方向の歩幅[m]", "float")
    duration: float                  = _param_field(5.0,  "動作期間[秒]", "float")
    forward_lean_angle: float        = _param_field(0.0,  "歩行中の前傾角度[度] (0=直立、正値で前傾)", "float")
    shoulder_roll_angle: float       = _param_field(10.0, "歩行中の両肩ロール角度[度]", "float")
    arm_swing_angle: float           = _param_field(20.0, "歩行中の腕ピッチ振り幅[度]", "float")
    smooth_stop: bool                = _param_field(False, "停止時に一歩追加してから止まるか", "bool")
    mix_enable: bool                 = _param_field(False, "ロール角を足首に反映するか", "bool")
    mix_gyro_g: float                = _param_field(0.001, "ジャイロミキシングゲイン係数", "float")
    term_foot_land: float            = _param_field(0.10, "着地期間比率", "float")
    term_foot_weight_shift: float    = _param_field(0.35, "重心移動期間比率", "float")
    term_land_stride: float          = _param_field(0.10, "前後/左右/旋回の着地期間比率", "float")
    foot_stride_max: float             = _param_field(0.025, "前後移動最大[m]", "float")
    foot_side_max: float            = _param_field(0.025, "左右移動最大[m]", "float")

@dataclass
class LinkParams:
    # melissa_mjcf.xml の左右脚body posから算出した実リンク長。
    # hip pitch→knee: hypot(0.014455, 0.057838)
    # knee→ankle pitch: hypot(0.022945, 0.055438)
    THIGH_LENGTH: float           = _param_field(0.05961695, "太ももの長さ[m]", "float")
    SHANK_LENGTH: float           = _param_field(0.05999871, "すねの長さ[m]", "float")
    # Melissaではankle pitchとfoot rollが同一位置。足裏はroll軸から36 mm下。
    ANKLE_LENGTH: float           = _param_field(0.0,   "足首ピッチから足首ロールまでの長さ[m]", "float")
    ANKLE_TO_FOOT: float          = _param_field(0.036, "足首ロール軸から足裏までの距離[m]", "float")
    # ROID1の20 mmを脚リンク長比 (119.616/130.0) で縮尺。
    SHORTEN_LEG_LENGTH: float     = _param_field(0.01840, "短縮時の脚長[m]", "float")

    @property
    def TOTAL_LEG_LENGTH(self):
        return self.THIGH_LENGTH + self.SHANK_LENGTH + self.ANKLE_LENGTH

    @property
    def LINK_LEG_LENGTH(self):
        return self.THIGH_LENGTH + self.SHANK_LENGTH
def load_walk_params():
    params = WalkParams()
    for key, value in globals().get('WALK_PARAMS', {}).items():
        if hasattr(params, key):
            setattr(params, key, value)
    return params


def load_link_params():
    params = LinkParams()
    for key, value in globals().get('LINK_PARAMS', {}).items():
        if hasattr(params, key):
            setattr(params, key, value)
    return params

class WalkController:
    IDLE = 0
    WALK = 1

    def __init__(self, params=None, params_link=None, msg_size=90):
        self.params       = params       if params       is not None else load_walk_params()
        self.params_link  = params_link  if params_link  is not None else load_link_params()
        self.msg_size     = msg_size
        self.mot_sts      = self.IDLE
        self.w_sts        = 0
        self.t            = 0
        self.foot_ref_pitch = 0.0
        self.trq_on       = 1.0
        self.stop_requested  = False
        self.use_zero_stride = False
        self.jikuasi         = 1  # 0:右軸足, 1:左軸足
        self.fwct_time       = 0.0
        self.foot_h          = 0.0
        self.foot_h_max      = self.params.foot_lift
        self.foot_direction  = {"x": 0.0, "y": 0.0, "turn": 0.0}
        self.sp_leg          = {"x": 0.0, "y": 0.0}
        self.sw_leg          = {"x": 0.0, "y": 0.0}
        self.r_foot          = {"x": 0.0, "y": 0.0}
        self.l_foot          = {"x": 0.0, "y": 0.0}
        self.data         = [0.0] * msg_size
        self.buf_output   = [[0.0] * msg_size for _ in range(10000)]
        self.buf_input    = [[0.0] * msg_size for _ in range(10000)]
        self.buf_index    = 0
        self.background_thread = None
        self.stop_background   = False

    @staticmethod
    def _clamp(v: float, lo: float, hi: float) -> float:
        return max(lo, min(hi, v))

    @staticmethod
    def _smoothstep(v: float) -> float:
        v = max(0.0, min(1.0, v))
        return v * v * (3.0 - 2.0 * v)

    @property
    def walk_cycle_time(self) -> float:
        """軸足を1回交代する時間。全歩行周期の半分。"""
        return max(self.params.cycle_duration * 0.5, 1e-6)

    def set_walk_direction(self, fwd: float, lat: float, turn: float) -> None:
        self.foot_direction["x"] = float(fwd) * self.params.foot_stride_max
        self.foot_direction["y"] = float(lat) * self.params.foot_side_max
        self.foot_direction["turn"] = float(turn) * MAX_TURN_STRIDE_DEG

    def hip_yaw_equivalent(self) -> float:
        """RX+は右、RX-は左のROID1股関節ヨー相当値[deg]を返す。"""
        p = self.params
        phase = self.fwct_time / self.walk_cycle_time
        ls = self._clamp(p.term_land_stride, 0.01, 0.45)
        le = 1.0 - ls
        turn = self.foot_direction["turn"]
        if turn == 0.0:
            return 0.0

        first_leg = 1 if turn > 0.0 else 0
        is_first_cycle = self.jikuasi == first_leg
        amplitude = abs(turn)
        value = 0.0
        if phase < ls:
            if not is_first_cycle:
                value = amplitude
        elif phase <= le:
            lp = (phase - ls) / max(le - ls, 1e-6)
            if is_first_cycle and lp > 0.5:
                value = amplitude * ((lp - 0.5) / 0.5)
            elif not is_first_cycle:
                value = amplitude * (1.0 - lp)
        elif is_first_cycle:
            value = amplitude
        return math.copysign(value, turn)

    def foot_up(self) -> None:
        p = self.params
        cycle = self.walk_cycle_time
        phase = self.fwct_time / cycle
        land = self._clamp(p.term_foot_land, 0.01, 0.45)
        weight = self._clamp(p.term_foot_weight_shift, land, 0.9)

        if phase <= land:
            self.foot_h = 0.0
        elif phase <= weight:
            self.foot_h = 0.0
        elif phase <= 1.0 - land:
            denom = max((1.0 - land) - weight, 1e-6)
            k = (phase - weight) / denom
            self.foot_h = self.foot_h_max * math.sin(math.pi * k)
        else:
            denom = max(land, 1e-6)
            k = (1.0 - phase) / denom
            self.foot_h = self.foot_h_max * 0.3 * math.sin(math.pi * k)

    def feet_direction_x(self) -> None:
        p = self.params
        cycle = self.walk_cycle_time
        phase = self.fwct_time / cycle
        ls = self._clamp(p.term_land_stride, 0.01, 0.45)
        le = 1.0 - ls
        x = self.foot_direction["x"]

        # 軸足は +x→-x、遊脚は -x→+x。交代時には互いの終点が次の始点となる。
        self.sp_leg["x"] = x * (1.0 - 2.0 * self._smoothstep(phase))
        swing = self._smoothstep((phase - ls) / max(le - ls, 1e-6))
        self.sw_leg["x"] = x * (2.0 * swing - 1.0)

    def feet_direction_y(self) -> None:
        p = self.params
        cycle = self.walk_cycle_time
        phase = self.fwct_time / cycle
        ls = self._clamp(p.term_land_stride, 0.01, 0.45)
        le = 1.0 - ls
        y = self.foot_direction["y"]

        self.r_foot["y"] = 0.0
        self.l_foot["y"] = 0.0
        if y == 0.0:
            return

        first_leg = 1 if y > 0 else 0
        is_first_cycle = (self.jikuasi == first_leg)
        ay = abs(y)

        if phase < ls:
            return
        if phase <= le:
            lp = (phase - ls) / max(le - ls, 1e-6)
            if is_first_cycle and lp > 0.5:
                op = (lp - 0.5) / 0.5
                # PhysicalOnでは右脚ロール軸が反転されるため、Meridim指令は
                # 左右とも正にすると実機座標上で左右外向きの開脚になる。
                self.r_foot["y"] = ay * op
                self.l_foot["y"] = ay * op
            return

        if is_first_cycle:
            rp = (phase - le) / max(1.0 - le, 1e-6)
            if y > 0:
                self.r_foot["y"] = ay * (1.0 - rp)
                self.l_foot["y"] = ay
            else:
                self.r_foot["y"] = ay
                self.l_foot["y"] = ay * (1.0 - rp)

    def counterCont(self, dt: float) -> None:
        cycle = self.walk_cycle_time
        self.fwct_time += dt
        if self.fwct_time >= cycle:
            self.fwct_time -= cycle
            self.jikuasi ^= 1

            k = self.sw_leg["y"]
            self.sw_leg["y"] = self.sp_leg["y"]
            self.sp_leg["y"] = k

            k = self.sw_leg["x"]
            self.sw_leg["x"] = self.sp_leg["x"]
            self.sp_leg["x"] = k

    def calculate_foot_height(self, phase, step_height):
        normalized_phase = ((phase % (2 * math.pi)) + 2 * math.pi) % (2 * math.pi)
        swing_duration = self.params.swing_ratio * 2.0 * math.pi
        swing_start    = math.pi - swing_duration / 2
        swing_end      = math.pi + swing_duration / 2
        if swing_start <= normalized_phase <= swing_end:
            swing_phase = (normalized_phase - swing_start) / swing_duration
            return step_height * math.sin(swing_phase * math.pi)
        return 0.0

    def calculate_forward_motion(self, phase, step_length):
        return step_length * math.sin(phase)

    def calculate_turn_motion(self, phase, turn_angle):
        return turn_angle * math.sin(phase)

    def apply_gyro_mixing(self, data: list, r: list) -> None:
        """IMUジャイロ角速度を元に足首・股関節ピッチ/ロールを補正する。
        WalkParams.mix_enable=True / mix_gyro_g で強度調整。
        r は Meridim90 フィードバック配列 (r[5]=gx*100, r[6]=gy*100)。
        """
        if not self.params.mix_enable:
            return
        g  = self.params.mix_gyro_g
        gy = float(r[6]) / 100.0   # ピッチ角速度 [deg/s]
        gx = float(r[5]) / 100.0   # ロール角速度 [deg/s]

        # ピッチ補正 — 足首ピッチ + 股関節ピッチ (半強度)
        pc = -gy * g
        data[IDX_L_ANKLE_P]   += pc;      data[IDX_R_ANKLE_P]   += pc
        data[IDX_L_HIP_PITCH] += pc * 0.5; data[IDX_R_HIP_PITCH] += pc * 0.5

        # ロール補正 — 足首ロール (左右逆方向)
        rc = gx * g
        data[IDX_L_ANKLE_ROLL] +=  rc
        data[IDX_R_ANKLE_ROLL] -=  rc

    def geometric_leg_ik(self, target_pos, target_roll=None, target_pitch=None,
                         is_left=True):
        if np.linalg.norm(target_pos) > self.params_link.TOTAL_LEG_LENGTH:
            logger.warning("geometric_leg_ik: leg length exceeded TOTAL_LEG_LENGTH")
            return None
        actual_leg_length = math.sqrt(target_pos[1]**2 + target_pos[2]**2)
        hip_roll = math.atan2(target_pos[1], actual_leg_length)
        MAX_ROLL = math.pi / 4
        hip_roll = max(-MAX_ROLL, min(MAX_ROLL, hip_roll))
        xz_proj  = math.sqrt(target_pos[0]**2 + target_pos[2]**2)
        cos_knee = (self.params_link.THIGH_LENGTH**2 + self.params_link.SHANK_LENGTH**2 - xz_proj**2) / \
                   (2 * self.params_link.THIGH_LENGTH * self.params_link.SHANK_LENGTH)
        knee_pitch  = math.pi - math.acos(max(-1.0, min(1.0, cos_knee)))
        if knee_pitch == 0.0:
            logger.warning("geometric_leg_ik: knee pitch is zero")
            return None
        leg_angle   = math.atan2(target_pos[0], target_pos[2])
        thigh_pitch = leg_angle - knee_pitch / 2.0
        ankle_pitch = -(leg_angle + knee_pitch / 2.0)
        ankle_roll  = -hip_roll
        if target_roll is not None:
            corr      = target_roll * 0.5
            hip_roll  = max(-MAX_ROLL, min(MAX_ROLL, hip_roll  + corr))
            ankle_roll = max(-MAX_ROLL, min(MAX_ROLL, ankle_roll - corr))
        if target_pitch is not None:
            ankle_pitch += target_pitch
        # Melissaの脚は股関節ヨーを持たない5軸構成。
        return np.array([hip_roll, thigh_pitch, knee_pitch, ankle_pitch, ankle_roll])

    def compute_walking_pose(self):
        p  = self.params
        pl = self.params_link
        waist_yaw_deg = 0.0
        if self.w_sts == 0 or self.w_sts == 1:
            z = pl.LINK_LEG_LENGTH - pl.SHORTEN_LEG_LENGTH
            l_pos = np.array([0.0, 0.0, z])
            r_pos = np.array([0.0, 0.0, z])
            l_ang = self.geometric_leg_ik(l_pos, is_left=True)
            r_ang = self.geometric_leg_ik(r_pos, is_left=False)
        else:
            phase_y = 2 * math.pi * ((self.t - p.init_wait_time) / p.cycle_duration)
            phase_z = 2 * math.pi * ((self.t - (p.init_wait_time + p.cycle_duration * p.weight_shift_duration_ratio)) / p.cycle_duration)
            if self.w_sts == 2:
                lat = p.hip_swing * math.sin(phase_y) * p.lateral_swing_ratio_1st
                l_fw = r_fw = l_lift = r_lift = 0.0
            else:
                norm_z = ((phase_z % (2 * math.pi)) + 2 * math.pi) % (2 * math.pi)
                at_start = norm_z < 0.3 * math.pi
                if p.smooth_stop:
                    if self.stop_requested and not self.use_zero_stride and at_start:
                        self.use_zero_stride = True
                else:
                    if self.stop_requested and not self.use_zero_stride:
                        self.use_zero_stride = True
                lat    = p.hip_swing * math.sin(phase_y)
                l_lift = self.calculate_foot_height(phase_z, p.foot_lift)
                r_lift = self.calculate_foot_height(phase_z + p.phase_offset, p.foot_lift)
                if self.use_zero_stride:
                    self.foot_direction["x"] = 0.0
                    self.foot_direction["y"] = 0.0
                    l_fw = r_fw = 0.0
                else:
                    self.counterCont(p.frame_interval)
                    self.foot_up()
                    self.feet_direction_x()
                    self.feet_direction_y()
                    # ROID1のRX+右股関節ヨー／RX-左股関節ヨー相当動作を、
                    # Melissaでは旋回方向が一致するよう腰ヨーへ逆符号で移す。
                    waist_yaw_deg = -self.hip_yaw_equivalent()

                    if self.jikuasi == 0:  # 右軸足
                        self.sp_leg["y"] = self.r_foot["y"]
                        self.sw_leg["y"] = self.l_foot["y"]
                    else:  # 左軸足
                        self.sp_leg["y"] = self.l_foot["y"]
                        self.sw_leg["y"] = self.r_foot["y"]

                    if self.jikuasi == 0:  # 右軸足
                        r_fw = self.sp_leg["x"]
                        r_lat = self.sp_leg["y"]
                        l_fw = self.sw_leg["x"]
                        l_lat = self.sw_leg["y"]
                        r_lift = 0.0
                        l_lift = self.foot_h
                    else:  # 左軸足
                        l_fw = self.sp_leg["x"]
                        l_lat = self.sp_leg["y"]
                        r_fw = self.sw_leg["x"]
                        r_lat = self.sw_leg["y"]
                        l_lift = 0.0
                        r_lift = self.foot_h

            z = pl.LINK_LEG_LENGTH - pl.SHORTEN_LEG_LENGTH
            if self.w_sts == 3 and not self.use_zero_stride:
                l_pos = np.array([l_fw, l_lat, z - l_lift])
                r_pos = np.array([r_fw, r_lat, z - r_lift])
            else:
                l_pos = np.array([l_fw,  -lat, z - l_lift])
                r_pos = np.array([r_fw,   lat, z - r_lift])
            l_ang = self.geometric_leg_ik(
                l_pos, target_pitch=self.foot_ref_pitch, target_roll=0.0,
                is_left=True,
            )
            r_ang = self.geometric_leg_ik(
                r_pos, target_pitch=self.foot_ref_pitch, target_roll=0.0,
                is_left=False,
            )

        if l_ang is not None and r_ang is not None:
            for idx, angle in zip(MELISSA_LEFT_LEG_INDICES, l_ang):
                self.data[idx - 1] = float(self.trq_on)
                self.data[idx] = float(math.degrees(angle))
            for idx, angle in zip(MELISSA_RIGHT_LEG_INDICES, r_ang):
                self.data[idx - 1] = float(self.trq_on)
                self.data[idx] = float(math.degrees(angle))
        if self.w_sts >= 2 and p.forward_lean_angle != 0.0:
            self.data[35] -= p.forward_lean_angle
            self.data[65] -= p.forward_lean_angle
        if self.w_sts >= 1:
            self.data[IDX_C_CHEST - 1] = float(self.trq_on)
            self.data[IDX_C_CHEST] = waist_yaw_deg
            self.data[24] = float(self.trq_on);  self.data[25] = float(p.shoulder_roll_angle)
            self.data[54] = float(self.trq_on);  self.data[55] = float(p.shoulder_roll_angle)
            self.data[28] = float(self.trq_on);  self.data[29] = -90.0
            self.data[58] = float(self.trq_on);  self.data[59] = -90.0
            #歩行時の両肩のピッチ軸のベースを20度にしたい
            self.data[22] = float(self.trq_on);  self.data[23] = 20.0
            self.data[52] = float(self.trq_on);  self.data[53] = 20.0

    def update_walking_state(self):
        p = self.params
        if self.t < p.init_wait_time:
            self.w_sts = 0
        elif self.t < p.init_wait_time + p.cycle_duration * p.landing_period_ratio:
            self.w_sts = 1
        elif self.t < p.init_wait_time + p.cycle_duration * p.weight_shift_duration_ratio:
            self.w_sts = 2
        else:
            self.w_sts = 3

    def start_walk(self, lx: float = 0.0, rx: float = 0.0):
        self.mot_sts  = self.WALK
        self.fwct_time = 0.0
        # 左右移動・旋回のうち入力が大きい方向に対応する軸足から開始する。
        initial_direction = lx if abs(lx) >= abs(rx) else rx
        self.jikuasi = 1 if initial_direction >= 0.0 else 0
        self.foot_h = 0.0
        self.sp_leg = {"x": 0.0, "y": 0.0}
        self.sw_leg = {"x": 0.0, "y": 0.0}
        self.r_foot = {"x": 0.0, "y": 0.0}
        self.l_foot = {"x": 0.0, "y": 0.0}
        self.data[20] = float(self.trq_on)
        self.buf_output = [[0.0] * self.msg_size for _ in range(10000)]
        self.buf_input  = [[0.0] * self.msg_size for _ in range(10000)]
        self.buf_index  = 0

    def stop_walk(self):
        self.mot_sts = self.IDLE
        z   = self.params_link.LINK_LEG_LENGTH - self.params_link.SHORTEN_LEG_LENGTH
        la  = self.geometric_leg_ik(np.array([0.0, 0.0, z]), is_left=True)
        ra  = self.geometric_leg_ik(np.array([0.0, 0.0, z]), is_left=False)
        if la is not None and ra is not None:
            for idx, angle in zip(MELISSA_LEFT_LEG_INDICES, la):
                self.data[idx - 1] = float(self.trq_on)
                self.data[idx] = float(math.degrees(angle))
            for idx, angle in zip(MELISSA_RIGHT_LEG_INDICES, ra):
                self.data[idx - 1] = float(self.trq_on)
                self.data[idx] = float(math.degrees(angle))
        self.data[22] = float(self.trq_on);  self.data[23] = 0.0   # L shoulder pitch → 0
        self.data[24] = float(self.trq_on);  self.data[25] = 0.0   # L shoulder roll  → 0
        self.data[52] = float(self.trq_on);  self.data[53] = 0.0   # R shoulder pitch → 0
        self.data[54] = float(self.trq_on);  self.data[55] = 0.0   # R shoulder roll  → 0
        self.data[IDX_C_CHEST - 1] = float(self.trq_on)
        self.data[IDX_C_CHEST] = 0.0

    def reset_pose(self):
        self.mot_sts = self.IDLE
        self.data = [0.0] * self.msg_size
        for idx in MELISSA_SERVO_INDICES:
            self.data[idx - 1] = float(self.trq_on)
            self.data[idx] = 0.0


# LMEのFunction Jumpから呼ぶMelissa歩行更新。
def _pad_axes():
    if _bhv_commander is None:
        return 0.0, 0.0, 0.0, 0.0
    with _bhv_commander._pad_lock:
        pad = list(_bhv_commander._pad) if _bhv_commander._pad is not None else None
    if not pad or len(pad) < 24:
        return 0.0, 0.0, 0.0, 0.0
    return (
        float(pad[PAD_AXIS_LY]),
        float(pad[PAD_AXIS_LX]),
        float(pad[PAD_AXIS_RX]),
        float(pad[PAD_AXIS_RY]),
    )


def _apply_arm_pitch(walk, right_y):
    arm_pitch = -max(-1.0, min(1.0, float(right_y))) * MAX_ARM_PITCH_DEG
    walk.data[IDX_L_SHOULDER_PITCH - 1] = float(walk.trq_on)
    walk.data[IDX_L_SHOULDER_PITCH] = arm_pitch
    walk.data[IDX_R_SHOULDER_PITCH - 1] = float(walk.trq_on)
    walk.data[IDX_R_SHOULDER_PITCH] = arm_pitch


def walk_ik_step() -> None:
    if _bhv_commander is None:
        return
    walk = _bhv_commander.controller
    if walk is None:
        return

    fwd, lat, turn, right_y = _pad_axes()
    walk_active = (abs(lat) + abs(fwd) + abs(turn)) >= STICK_DEAD
    _bhv_commander._variables['UserVal_0'] = 1 if walk_active else 0
    if walk_active:
        if walk.mot_sts != WalkController.WALK:
            walk.t = 0.0
            walk.stop_requested = False
            walk.use_zero_stride = False
            walk.start_walk(lx=lat, rx=turn)
        raw_fwd = fwd * MAX_FWD_STRIDE
        walk.params.forward_stride = max(
            -FOOT_SLIDE_MAX_FWD, min(FOOT_SLIDE_MAX_FWD, raw_fwd)
        )
        walk.set_walk_direction(fwd, lat, turn)
        walk.update_walking_state()
        walk.compute_walking_pose()
        walk.t += 1.0 / LOOP_HZ
        if walk.params.mix_enable:
            walk.apply_gyro_mixing(walk.data, _bhv_commander._imu)
    elif walk.mot_sts == WalkController.WALK:
        walk.set_walk_direction(0.0, 0.0, 0.0)
        walk.stop_walk()
    _apply_arm_pitch(walk, right_y)


def user_setup() -> None:
    if _bhv_commander is not None:
        ctrl = _bhv_commander.controller
        if ctrl is not None:
            ctrl.reset_pose()
    logger.info('Logic cartridge: ready (Melissa walk IK)')


def user_logic(r: list, s: list) -> list:
    pad_raw = _decode_meridim_pad(s)
    fwd = float(pad_raw[PAD_AXIS_LY])
    lat = float(pad_raw[PAD_AXIS_LX])
    turn = float(pad_raw[PAD_AXIS_RX])
    if _bhv_commander is not None:
        _bhv_commander._variables['UserVal_0'] = 1 if abs(fwd) >= STICK_DEAD else 0
        _bhv_commander._variables['UserVal_2'] = 1 if abs(turn) >= TURN_STICK_DEAD else 0
        _bhv_commander._variables['UserVal_3'] = 1 if abs(lat) >= SIDE_STICK_THRESH else 0
        _bhv_commander.set_imu(r)
        _bhv_commander.set_pad(pad_raw)
        _bhv_commander.poll_and_update()
        return _bhv_commander.get_last_output()
    return list(s)

def _lme_ensure_boot() -> None:
    if _bhv_commander is None:
        return
    if getattr(_bhv_commander, '_motion', None) is not None:
        return
    _ctrl = getattr(_bhv_commander, 'controller', None) or getattr(_bhv_commander, 'walk', None)
    if hasattr(_ctrl, 'reset_pose'):
        _ctrl.reset_pose()
    _bhv_commander._trigger_motion(MOTION_BOOT, 'Boot')

_lme_user_setup = user_setup
def user_setup() -> None:
    _lme_user_setup()
    _lme_ensure_boot()
